language: node_js
node_js:
- '8'
sudo: false
dist: trusty
addons:
  chrome: stable
cache:
  directories:
  - "$HOME/.npm"
before_install:
- npm config set spin false
notifications:
  slack:
    secure: fcmzm2WT5gctDH8Ch7ACKqdWRtVEkrDj2KVw6uVHVZp5UENOIurEfM7VWI1tlHfHHUsbXkug6Djtno2xYAOiWN5GGWGAr4QsVAOdPRwZRhrpCTagreIVFGFOA8zxZOqpyOPEiWn+svqD4x523DJ8HyWl2oAaLkRf+66D2BMCr+a5A+qis8yrGrYWQzIy/56CJlEoSDowahzOkFaz1uEcfMHVOpNnK/OoebszKFqff2UlHDmvZpS3oXw6W4CwkvTtvAgXy1GctbVTiEiaJkMZYpGOKihXczaKbx76jAepejxFSA0SzlfxF8vrlfSzukC8SGGH+Ob4Mqfke9kRqkmb77kEg7342pjq86G1iXgiqAcN/+IrH7Dza2asZnHH4FUejgGOesmgbWVm2/gYL4a6wdNT1d7O9ALXikDEF3ZSEoZYbFFKS1Gvy0hXXIFGqTm+9jJuLg0Jd8QmyhcnvhNFgqiS3DxuNoIMVSA7TcnFZp8DWRRkzuOA7S1c5MYWwbGlllrJLK0dETqL09pvrj8aGvxWA+a51X5WduXW4ArMqZdsxCLtcgfhm5u4m2140bKWICskSIgFGlEYCNsDz+MwcHMGBZX/mcdr4NnmVHsGDHJqEz2PTpRqnFmiiJp9pS3BxMDyIraiFxtkyVj/OTC0zowPKDMWS+z9R+R+04ni17o=
  email: false
